from ftruck_etl_utils import load_fule_truck_agg_data, load_fule_truck_stats_data
import matplotlib.pyplot as plt
from sklearn.preprocessing import minmax_scale
import seaborn as sns


# ['vid', 'harsh_acc', 'harsh_dec', 'harsh_turn', 'idle', 'over_speed']
def hist_aggressive_behaviors():
    data = load_fule_truck_agg_data()
    print(data.head(2))
    # scale
    data = minmax_scale(data)
    # plt.ylabel('No.')
    plt.subplot(321)
    plt.hist(data[:,1],bins=100)
    # plt.xlabel('time (s)')
    plt.ylabel('No. of trips')
    plt.title('Distribution of No.harsh_acceleration per 100Km')
    plt.subplot(322)
    plt.hist(data[:,2],bins=100)
    plt.ylabel('No. of trips')
    plt.title('Distribution of No.harsh_deceleration per 100Km')
    plt.subplot(323)
    plt.hist(data[:,3],bins=100)
    plt.ylabel('No. of trips')
    plt.title('Distribution of No.harsh_turn per 100Km')
    plt.subplot(324)
    plt.hist(data[:,4],bins=100)
    plt.ylabel('No. of trips')
    plt.title('Distribution of No.idling per 100Km')
    plt.subplot(325)
    plt.hist(data[:,5],bins=100)
    plt.ylabel('No. of trips')
    plt.title('Distribution of No.over_speed per 100Km')
    plt.show()


def hist_statistics():
    cols = ['vid','meanSpeed', 'stddevSpeed', 'meanRpm', 'stddevRpm',
            'idleRate', 'meanAngleSpeed', 'stddevAngleSpeed',
            'tripDurationHours', 'tripMileKm']
    data = load_fule_truck_stats_data()
    print(data.head(2))
    # scale
    data = minmax_scale(data)
    # plt.ylabel('No.')
    plt.subplot(331)
    plt.hist(data[:,1],bins=100)
    plt.ylabel('No. of trips')
    plt.title('Distribution of average speed')
    plt.subplot(332)
    plt.hist(data[:,2],bins=100)
    plt.ylabel('No. of trips')
    plt.title('Distribution of stddev speed')
    plt.subplot(333)
    plt.hist(data[:,3],bins=100)
    plt.ylabel('No. of trips')
    plt.title('Distribution of average RPM')
    plt.subplot(334)
    plt.hist(data[:,4],bins=100)
    plt.ylabel('No. of trips')
    plt.title('Distribution of stddev RPM')
    plt.subplot(335)
    plt.hist(data[:,5],bins=100)
    plt.ylabel('No. of trips')
    plt.title('Distribution of idle rate')
    plt.subplot(336)
    plt.hist(data[:,6],bins=100)
    plt.ylabel('No. of trips')
    plt.title('Distribution of avg. angle speed')
    plt.subplot(337)
    plt.hist(data[:,7],bins=100)
    plt.ylabel('No. of trips')
    plt.title('Distribution of stddev. angle speed')
    plt.subplot(338)
    plt.hist(data[:,8],bins=100)
    plt.ylabel('No. of trips')
    plt.title('Distribution of trip duration')
    plt.subplot(339)
    plt.hist(data[:,9],bins=100)
    plt.ylabel('No. of trips')
    plt.title('Distribution of trip distance')
    plt.show()

def hist_aggressive_behaviors02():
    data = load_fule_truck_agg_data()
    print(data.head(2))
    # scale
    data = minmax_scale(data)
    # plt.ylabel('No.')
    plt.subplot(321)
    sns.distplot(data[:,1])
    # plt.xlabel('time (s)')
    plt.ylabel('No. of trips')
    plt.title('Distribution of No.harsh_acceleration per 100Km')
    plt.subplot(322)
    sns.distplot(data[:,2])
    plt.ylabel('No. of trips')
    plt.title('Distribution of No.harsh_deceleration per 100Km')
    plt.subplot(323)
    sns.distplot(data[:,3])
    plt.ylabel('No. of trips')
    plt.title('Distribution of No.harsh_turn per 100Km')
    plt.subplot(324)
    sns.distplot(data[:,4])
    plt.ylabel('No. of trips')
    plt.title('Distribution of No.idling per 100Km')
    plt.subplot(325)
    sns.distplot(data[:,5])
    plt.ylabel('No. of trips')
    plt.title('Distribution of No.over_speed per 100Km')
    plt.show()


if __name__ == '__main__':
    hist_aggressive_behaviors02()
    # hist_statistics()